# foobar.yaml

AMQP_URI: 'amqp://admin:rabbit@localhost'

LOGGING:
    version: 1
    handlers:
        console:
            class: logging.StreamHandler
    root:
        level: DEBUG
        handlers: [console]
